//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logic.TeacherServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TeacherSelect", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DataContracts")]
    [System.SerializableAttribute()]
    public partial class TeacherSelect : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeacherSortDirctionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeacherSortNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentPage {
            get {
                return this.CurrentPageField;
            }
            set {
                if ((this.CurrentPageField.Equals(value) != true)) {
                    this.CurrentPageField = value;
                    this.RaisePropertyChanged("CurrentPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeacherSortDirction {
            get {
                return this.TeacherSortDirctionField;
            }
            set {
                if ((object.ReferenceEquals(this.TeacherSortDirctionField, value) != true)) {
                    this.TeacherSortDirctionField = value;
                    this.RaisePropertyChanged("TeacherSortDirction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeacherSortName {
            get {
                return this.TeacherSortNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TeacherSortNameField, value) != true)) {
                    this.TeacherSortNameField = value;
                    this.RaisePropertyChanged("TeacherSortName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TeacherManage", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DataContracts")]
    [System.SerializableAttribute()]
    public partial class TeacherManage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AvgScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EffectiveTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExamNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExamineeCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfQualifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PassRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuestionQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RowNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AvgScore {
            get {
                return this.AvgScoreField;
            }
            set {
                if ((this.AvgScoreField.Equals(value) != true)) {
                    this.AvgScoreField = value;
                    this.RaisePropertyChanged("AvgScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EffectiveTime {
            get {
                return this.EffectiveTimeField;
            }
            set {
                if ((this.EffectiveTimeField.Equals(value) != true)) {
                    this.EffectiveTimeField = value;
                    this.RaisePropertyChanged("EffectiveTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExamName {
            get {
                return this.ExamNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ExamNameField, value) != true)) {
                    this.ExamNameField = value;
                    this.RaisePropertyChanged("ExamName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExamineeCount {
            get {
                return this.ExamineeCountField;
            }
            set {
                if ((this.ExamineeCountField.Equals(value) != true)) {
                    this.ExamineeCountField = value;
                    this.RaisePropertyChanged("ExamineeCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfQualified {
            get {
                return this.NumOfQualifiedField;
            }
            set {
                if ((this.NumOfQualifiedField.Equals(value) != true)) {
                    this.NumOfQualifiedField = value;
                    this.RaisePropertyChanged("NumOfQualified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PassRate {
            get {
                return this.PassRateField;
            }
            set {
                if ((this.PassRateField.Equals(value) != true)) {
                    this.PassRateField = value;
                    this.RaisePropertyChanged("PassRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuestionQuantity {
            get {
                return this.QuestionQuantityField;
            }
            set {
                if ((this.QuestionQuantityField.Equals(value) != true)) {
                    this.QuestionQuantityField = value;
                    this.RaisePropertyChanged("QuestionQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RowNumber {
            get {
                return this.RowNumberField;
            }
            set {
                if ((this.RowNumberField.Equals(value) != true)) {
                    this.RowNumberField = value;
                    this.RaisePropertyChanged("RowNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExamSelect", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DataContracts")]
    [System.SerializableAttribute()]
    public partial class ExamSelect : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExamIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SortFieldsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SortWayField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExamId {
            get {
                return this.ExamIdField;
            }
            set {
                if ((this.ExamIdField.Equals(value) != true)) {
                    this.ExamIdField = value;
                    this.RaisePropertyChanged("ExamId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageIndex {
            get {
                return this.PageIndexField;
            }
            set {
                if ((this.PageIndexField.Equals(value) != true)) {
                    this.PageIndexField = value;
                    this.RaisePropertyChanged("PageIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SortFields {
            get {
                return this.SortFieldsField;
            }
            set {
                if ((object.ReferenceEquals(this.SortFieldsField, value) != true)) {
                    this.SortFieldsField = value;
                    this.RaisePropertyChanged("SortFields");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SortWay {
            get {
                return this.SortWayField;
            }
            set {
                if ((object.ReferenceEquals(this.SortWayField, value) != true)) {
                    this.SortWayField = value;
                    this.RaisePropertyChanged("SortWay");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExamDetails", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DataContracts")]
    [System.SerializableAttribute()]
    public partial class ExamDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExamScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IsPassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PassCriteriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExamScore {
            get {
                return this.ExamScoreField;
            }
            set {
                if ((this.ExamScoreField.Equals(value) != true)) {
                    this.ExamScoreField = value;
                    this.RaisePropertyChanged("ExamScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsPass {
            get {
                return this.IsPassField;
            }
            set {
                if ((this.IsPassField.Equals(value) != true)) {
                    this.IsPassField = value;
                    this.RaisePropertyChanged("IsPass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PassCriteria {
            get {
                return this.PassCriteriaField;
            }
            set {
                if ((this.PassCriteriaField.Equals(value) != true)) {
                    this.PassCriteriaField = value;
                    this.RaisePropertyChanged("PassCriteria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowNumber {
            get {
                return this.RowNumberField;
            }
            set {
                if ((this.RowNumberField.Equals(value) != true)) {
                    this.RowNumberField = value;
                    this.RaisePropertyChanged("RowNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalScore {
            get {
                return this.TotalScoreField;
            }
            set {
                if ((this.TotalScoreField.Equals(value) != true)) {
                    this.TotalScoreField = value;
                    this.RaisePropertyChanged("TotalScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.rick.com/", ConfigurationName="TeacherServiceReference.ITeacherService")]
    public interface ITeacherService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rick.com/ITeacherService/ExamList", ReplyAction="http://www.rick.com/ITeacherService/ExamListResponse")]
        Logic.TeacherServiceReference.TeacherManage[] ExamList(Logic.TeacherServiceReference.TeacherSelect teacherSelect);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rick.com/ITeacherService/ExamListCount", ReplyAction="http://www.rick.com/ITeacherService/ExamListCountResponse")]
        int ExamListCount(Logic.TeacherServiceReference.TeacherSelect teacherSelect);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rick.com/ITeacherService/ExamJoinDetails", ReplyAction="http://www.rick.com/ITeacherService/ExamJoinDetailsResponse")]
        Logic.TeacherServiceReference.ExamDetails[] ExamJoinDetails(Logic.TeacherServiceReference.ExamSelect examSelect);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITeacherServiceChannel : Logic.TeacherServiceReference.ITeacherService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TeacherServiceClient : System.ServiceModel.ClientBase<Logic.TeacherServiceReference.ITeacherService>, Logic.TeacherServiceReference.ITeacherService {
        
        public TeacherServiceClient() {
        }
        
        public TeacherServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TeacherServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TeacherServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TeacherServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Logic.TeacherServiceReference.TeacherManage[] ExamList(Logic.TeacherServiceReference.TeacherSelect teacherSelect) {
            return base.Channel.ExamList(teacherSelect);
        }
        
        public int ExamListCount(Logic.TeacherServiceReference.TeacherSelect teacherSelect) {
            return base.Channel.ExamListCount(teacherSelect);
        }
        
        public Logic.TeacherServiceReference.ExamDetails[] ExamJoinDetails(Logic.TeacherServiceReference.ExamSelect examSelect) {
            return base.Channel.ExamJoinDetails(examSelect);
        }
    }
}
