//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap BTN_Close_16x16 {
            get {
                object obj = ResourceManager.GetObject("BTN_Close_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BTN_PageLeft_20x15_png {
            get {
                object obj = ResourceManager.GetObject("BTN_PageLeft_20x15.png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BTN_PageRight_20x15_png_ {
            get {
                object obj = ResourceManager.GetObject("BTN_PageRight_20x15.png ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BTN_Radio_Selected_16x16_png {
            get {
                object obj = ResourceManager.GetObject("BTN_Radio_Selected_16x16.png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BTN_Radio_Unselected_16x16_png {
            get {
                object obj = ResourceManager.GetObject("BTN_Radio_Unselected_16x16.png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BTN_RemeberMe_Select_12x12 {
            get {
                object obj = ResourceManager.GetObject("BTN_RemeberMe_Select_12x12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BTN_RemeberMe_Unselect_12X12 {
            get {
                object obj = ResourceManager.GetObject("BTN_RemeberMe_Unselect_12X12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap head_logo {
            get {
                object obj = ResourceManager.GetObject("head_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap head_out {
            get {
                object obj = ResourceManager.GetObject("head_out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ICN_Avatar_130x110_png__ {
            get {
                object obj = ResourceManager.GetObject("ICN_Avatar_130x110.png  ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ICN_Client_Close_Program_21X21 {
            get {
                object obj = ResourceManager.GetObject("ICN_Client_Close_Program_21X21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ICN_Client_Close_Program_29X20 {
            get {
                object obj = ResourceManager.GetObject("ICN_Client_Close_Program_29X20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ICN_Client_Login_Wrong_20X20 {
            get {
                object obj = ResourceManager.GetObject("ICN_Client_Login_Wrong_20X20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ICN_Client_Max_Or_Normal_Program_22X22 {
            get {
                object obj = ResourceManager.GetObject("ICN_Client_Max_Or_Normal_Program_22X22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ICN_Client_Min_Program_22X22 {
            get {
                object obj = ResourceManager.GetObject("ICN_Client_Min_Program_22X22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ICN_Client_PersonalInformation_20x20 {
            get {
                object obj = ResourceManager.GetObject("ICN_Client_PersonalInformation_20x20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ICN_Client_PersonalInformation_20x201 {
            get {
                object obj = ResourceManager.GetObject("ICN_Client_PersonalInformation_20x201", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ICN_Decrese_10x15_png {
            get {
                object obj = ResourceManager.GetObject("ICN_Decrese_10x15.png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ICN_Increase_10x15_png {
            get {
                object obj = ResourceManager.GetObject("ICN_Increase_10x15.png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ICN_Password_20x15 {
            get {
                object obj = ResourceManager.GetObject("ICN_Password_20x15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ICN_Right_15x15 {
            get {
                object obj = ResourceManager.GetObject("ICN_Right_15x15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ICN_Search_15x20_png {
            get {
                object obj = ResourceManager.GetObject("ICN_Search_15x20.png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ICN_Usename_20x20 {
            get {
                object obj = ResourceManager.GetObject("ICN_Usename_20x20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ICN_Wrong_15x15 {
            get {
                object obj = ResourceManager.GetObject("ICN_Wrong_15x15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LOGO_Client_Login_40X300 {
            get {
                object obj = ResourceManager.GetObject("LOGO_Client_Login_40X300", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LOGO_Client_Titel_120x20 {
            get {
                object obj = ResourceManager.GetObject("LOGO_Client_Titel_120x20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LOGO_Client_Titel_120x20_black {
            get {
                object obj = ResourceManager.GetObject("LOGO_Client_Titel_120x20_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LOGO_Client_Titel_120x201 {
            get {
                object obj = ResourceManager.GetObject("LOGO_Client_Titel_120x201", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap username_show {
            get {
                object obj = ResourceManager.GetObject("username_show", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
